### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by driescollewaert** [bramoosterhuis/com.devolo#2]
Hi,

I cannot add a devolo wall switch to my homey. During pairing, the device is found, but then blocks at the 'Multichannel nodes worden opgehaald' stage. The switch becomes useless (only a reset is possible) and the switch is not added to homey. Any idea if this is a bug?

**Comment by bramoosterhuis** [comment]
Could be a bug, could be a feature :-). I just updated the app and I will start testing this afternoon. I keep you posted.

**Comment by bramoosterhuis** [comment]
I faced the issue as well, but it is somehow related to Homey's firmware. Hopefully, they release the update this Friday. 

see:
https://github.com/athombv/homey/issues/1261#issuecomment-283684650

**Comment by bramoosterhuis** [comment]
Update Homey to v1.2.0 using the experimental updates and your switch should pair with no issues.
