### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by twellocity** [bramoosterhuis/com.devolo#3]
I have the same pairing same issue.
 SW version 1.02
Devolo scene switch MT2652
Device not usable in Homey at the moment

**Comment by bramoosterhuis** [comment]
I just updated the app in the alpha channel, tonight I will try to test the device myself. Otherwise I can add you to the alpha release and help out testing the app.

**Comment by bramoosterhuis** [comment]
I faced the issue as well, but it is somehow related to Homey's firmware. Hopefully they release the update it this Friday. 

see:
https://github.com/athombv/homey/issues/1261#issuecomment-283684650

**Comment by bramoosterhuis** [comment]
Update Homey to v1.2.0 using the experimental updates and your switch should pair with no issues.
