### ISSUE TITLE
add support for further devices

### ISSUE THREAD

**Issue by ghamet** [bramoosterhuis/com.devolo#4]
Requesting support for Room Sensor DRS21 MT:2649 -- currently only supported by raw Z-wave connection to be switched on/off -- reading temperature, receiving temparature inc/dec request would be required
Requesting support for Metering and Switching plug MT:2646 -- currently not pairing, must have would be switching functionality, nice to  have - consumption measurement

**Comment by bramoosterhuis** [comment]
Yesterday I added initial support for those devices. I don't own those devices myself but I will add you to the alpha if you are interested in helping to test the app.

**Comment by ghamet** [comment]
Please add me. I'll see what I can get tested on the weekend.

**Comment by bramoosterhuis** [comment]
I submitted a beta release last week, it should become available as soon as Athom approves the app.
